
package dibujante;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Stack;

import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JToggleButton;
import javax.swing.filechooser.FileNameExtensionFilter;

import figuras.Anillo;
import figuras.Borrador;
import figuras.Circulo;
import figuras.Cometa;
import figuras.Corazon;
import figuras.Cruz;
import figuras.Cubeta;
import figuras.DibujoLibre;
import figuras.Escaleno;
import figuras.Estrella;
import figuras.Feria_1;
import figuras.Figura;
import figuras.FlechaAbajo;
import figuras.FlechaArriba;
import figuras.FlechaDerecha;
import figuras.FlechaIzquierda;
import figuras.Hexagono;
import figuras.Imagen;
import figuras.LineaRedimensionable;
import figuras.MediaLuna;
import figuras.Octagono;
import figuras.PacMan;
import figuras.Paralelograma;
import figuras.Pentagono;
import figuras.Rectangulo;
import figuras.Rombo;
import figuras.SemiCirculo;
import figuras.Trapecio;
import figuras.TrebolCuatroHojas;
import figuras.TrebolTresHojas;
import figuras.Triangulo;
import figuras.TrianguloRectangulo;

public class VentanaPrincipal extends javax.swing.JFrame {

	private final PanelDeDibujo panelDeDibujo;

        private Color colorSeleccionado;
	
        private List<String> figurasDisponibles;
	
        private String botonSeleccionado;

	public VentanaPrincipal() {
		
            initComponents();
	
            this.setExtendedState(this.MAXIMIZED_BOTH);
	
            setTitle("Dibujante - Nueva Imagen");

		setLocationRelativeTo(null);

		panelDeDibujo = new PanelDeDibujo();

		add(panelDeDibujo, BorderLayout.CENTER);
		panelDeDibujo.setVentanaPrincipal(this);

		panelColor1.setBackground(Color.BLACK);
		panelColor2.setBackground(Color.WHITE);

		botonSeleccionado = "";
		figurasDisponibles = listaFigurasDisponibles();
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoMenuItemFiguras = new javax.swing.ButtonGroup();
        grupoToogleButtons = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btn22 = new javax.swing.JToggleButton();
        btn20 = new javax.swing.JToggleButton();
        btn23 = new javax.swing.JToggleButton();
        panelColor1 = new javax.swing.JPanel();
        panelColor2 = new javax.swing.JPanel();
        comboGrosor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btn24 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        lblFigura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rotarIzquierda = new javax.swing.JToggleButton();
        centrar = new javax.swing.JToggleButton();
        anguloGiro = new javax.swing.JTextField();
        rotarDerecha = new javax.swing.JToggleButton();
        limpiarTodo = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vueltas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        anguloGiro360 = new javax.swing.JTextField();
        verRegla = new javax.swing.JCheckBox();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        vueltas1 = new javax.swing.JTextField();
        vueltas2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        efectoFigura = new javax.swing.JComboBox<>();
        efectoFigura1 = new javax.swing.JComboBox<>();
        figuraRellena = new javax.swing.JCheckBox();
        efectoFigura3 = new javax.swing.JComboBox<>();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        vueltas3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 170));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane2.setBackground(new java.awt.Color(245, 246, 247));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(105, 105));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(763, 165));

        jPanel2.setBackground(new java.awt.Color(245, 246, 247));
        jPanel2.setPreferredSize(new java.awt.Dimension(758, 125));

        grupoToogleButtons.add(btn22);
        btn22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        btn22.setContentAreaFilled(false);
        btn22.setOpaque(true);
        btn22.setToolTipText("Lapiz");
        btn22.setPreferredSize(new java.awt.Dimension(37, 30));
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        grupoToogleButtons.add(btn20);
        btn20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cubeta.png"))); // NOI18N
        btn20.setContentAreaFilled(false);
        btn20.setOpaque(true);
        btn20.setToolTipText("Cubeta");
        btn20.setPreferredSize(new java.awt.Dimension(37, 30));
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        grupoToogleButtons.add(btn23);
        btn23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/goteros.png"))); // NOI18N
        btn23.setContentAreaFilled(false);
        btn23.setToolTipText("Gotero");
        btn23.setOpaque(true);
        btn23.setPreferredSize(new java.awt.Dimension(37, 30));
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });

        panelColor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelColor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelColor1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelColor1Layout = new javax.swing.GroupLayout(panelColor1);
        panelColor1.setLayout(panelColor1Layout);
        panelColor1Layout.setHorizontalGroup(
            panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelColor1Layout.setVerticalGroup(
            panelColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        panelColor2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelColor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelColor2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelColor2Layout = new javax.swing.GroupLayout(panelColor2);
        panelColor2.setLayout(panelColor2Layout);
        panelColor2Layout.setHorizontalGroup(
            panelColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelColor2Layout.setVerticalGroup(
            panelColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        comboGrosor.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        comboGrosor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "4", "6", "8", "10", "12" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Grosor");

        grupoToogleButtons.add(btn24);
        btn24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrador.png"))); // NOI18N
        btn24.setContentAreaFilled(false);
        btn24.setOpaque(true);
        btn24.setToolTipText("Borrador");
        btn24.setPreferredSize(new java.awt.Dimension(37, 30));
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });

        grupoToogleButtons.add(jToggleButton1);
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen.png"))); // NOI18N
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setOpaque(true);
        jToggleButton1.setToolTipText("Insertar imagen.");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        lblFigura.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblFigura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFigura.setText("Lapiz");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("aaaa");

        grupoToogleButtons.add(rotarIzquierda);
        rotarIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rotate_180.png"))); // NOI18N
        rotarIzquierda.setContentAreaFilled(false);
        rotarIzquierda.setOpaque(true);
        jToggleButton1.setToolTipText("Insertar imagen.");
        rotarIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            //    rotarIzquierdaActionPerformed(evt);
            }
        });

        grupoToogleButtons.add(centrar);
        centrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/center.png"))); // NOI18N
        centrar.setContentAreaFilled(false);
        centrar.setOpaque(true);
        jToggleButton1.setToolTipText("Insertar imagen.");
        centrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
             //   centrarActionPerformed(evt);
            }
        });

        grupoToogleButtons.add(rotarDerecha);
        rotarDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rotate_180_r.png"))); // NOI18N
        rotarDerecha.setContentAreaFilled(false);
        rotarDerecha.setOpaque(true);
        jToggleButton1.setToolTipText("Insertar imagen.");
        rotarDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            //    rotarDerechaActionPerformed(evt);
            }
        });

        grupoToogleButtons.add(limpiarTodo);
        limpiarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Recycle_Bin_Full.png"))); // NOI18N
        limpiarTodo.setContentAreaFilled(false);
        limpiarTodo.setOpaque(true);
        jToggleButton1.setToolTipText("Insertar imagen.");
        limpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTodoActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fill.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lap.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grados.png"))); // NOI18N

        grupoToogleButtons.add(jToggleButton2);
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spray.png"))); // NOI18N
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.setOpaque(true);
        jToggleButton1.setToolTipText("Insertar imagen.");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regla.png"))); // NOI18N

        vueltas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueltas2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/move_top.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/move_down.png"))); // NOI18N

        efectoFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        efectoFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectoFiguraActionPerformed(evt);
            }
        });

        efectoFigura1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        efectoFigura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectoFigura1ActionPerformed(evt);
            }
        });

        figuraRellena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                figuraRellenaActionPerformed(evt);
            }
        });

        efectoFigura3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        efectoFigura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectoFigura3ActionPerformed(evt);
            }
        });

        grupoToogleButtons.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/text.png"))); // NOI18N
        jToggleButton4.setContentAreaFilled(false);
        jToggleButton4.setOpaque(true);
        jToggleButton1.setToolTipText("Insertar imagen.");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/angle.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelColor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(rotarIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(centrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(limpiarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rotarDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verRegla, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vueltas3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(vueltas2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vueltas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vueltas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anguloGiro360, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(anguloGiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(figuraRellena, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(efectoFigura3, javax.swing.GroupLayout.Alignment.LEADING, 0, 265, Short.MAX_VALUE)
                    .addComponent(efectoFigura, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(efectoFigura1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(lblFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anguloGiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verRegla, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vueltas2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limpiarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(efectoFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(figuraRellena, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(comboGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(efectoFigura3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vueltas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(efectoFigura1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anguloGiro360))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(panelColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rotarIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(centrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rotarDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(vueltas3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vueltas1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("", jPanel2);

        jPanel1.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Archivo");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Nuevo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Abrir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Edicion");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText(" Deshacer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Rehacer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rotarDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotarDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotarDerechaActionPerformed

    private void limpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarTodoActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void vueltas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueltas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vueltas2ActionPerformed

    private void efectoFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectoFiguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efectoFiguraActionPerformed

    private void efectoFigura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectoFigura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efectoFigura1ActionPerformed

    private void efectoFigura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectoFigura3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efectoFigura3ActionPerformed

    private void figuraRellenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_figuraRellenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_figuraRellenaActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		deshacer();
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		rehacer();
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		guardarImagen();
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem4ActionPerformed
		BufferedImage bimg = abrirImagen();
		if (bimg != null) {
			panelDeDibujo.getFiguras()
					.add(new Imagen(new Point(0, 0), bimg.getWidth(), bimg.getHeight(), Color.BLACK, bimg));
			panelDeDibujo.repaint();
		}
	}// GEN-LAST:event_jMenuItem4ActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		preguntarAntesDeCerrar();
	}// GEN-LAST:event_formWindowClosing

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem5ActionPerformed
		funcionBtnNuevo();
	}// GEN-LAST:event_jMenuItem5ActionPerformed

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton1ActionPerformed
		insertarImagenMovible();
	}// GEN-LAST:event_jToggleButton1ActionPerformed

	private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn24ActionPerformed
		botonSeleccionado = "Borrador";
		System.out.println(botonSeleccionado);
		lblFigura.setText(botonSeleccionado);
	}// GEN-LAST:event_btn24ActionPerformed

	private void panelColor2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_panelColor2MouseClicked
		seleccionarColorSecundario();
	}// GEN-LAST:event_panelColor2MouseClicked

	private void panelColor1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_panelColor1MouseClicked
		seleccionarColorPrimario();
	}// GEN-LAST:event_panelColor1MouseClicked

	private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn23ActionPerformed
		botonSeleccionado = "Gotero";
		System.out.println(botonSeleccionado);
		lblFigura.setText(botonSeleccionado);
	}// GEN-LAST:event_btn23ActionPerformed

	private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn20ActionPerformed
		botonSeleccionado = "Cubeta";
		System.out.println(botonSeleccionado);
		lblFigura.setText(botonSeleccionado);
	}// GEN-LAST:event_btn20ActionPerformed

	private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn22ActionPerformed
		botonSeleccionado = "Lapiz";
		System.out.println(botonSeleccionado);
		lblFigura.setText(botonSeleccionado);
	}// GEN-LAST:event_btn22ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VentanaPrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anguloGiro;
    private javax.swing.JTextField anguloGiro360;
    private javax.swing.JToggleButton btn20;
    private javax.swing.JToggleButton btn22;
    private javax.swing.JToggleButton btn23;
    private javax.swing.JToggleButton btn24;
    private javax.swing.JToggleButton centrar;
    private javax.swing.JComboBox<String> comboGrosor;
    private javax.swing.JComboBox<String> efectoFigura;
    private javax.swing.JComboBox<String> efectoFigura1;
    private javax.swing.JComboBox<String> efectoFigura3;
    private javax.swing.JCheckBox figuraRellena;
    private javax.swing.ButtonGroup grupoMenuItemFiguras;
    private javax.swing.ButtonGroup grupoToogleButtons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JLabel lblFigura;
    private javax.swing.JToggleButton limpiarTodo;
    public javax.swing.JPanel panelColor1;
    private javax.swing.JPanel panelColor2;
    private javax.swing.JToggleButton rotarDerecha;
    private javax.swing.JToggleButton rotarIzquierda;
    private javax.swing.JCheckBox verRegla;
    private javax.swing.JTextField vueltas;
    private javax.swing.JTextField vueltas1;
    private javax.swing.JTextField vueltas2;
    private javax.swing.JTextField vueltas3;
    // End of variables declaration//GEN-END:variables

	// Metodos para saber que se dibujara
	private void figuraADibujarseEnCadaBoton(Graphics g, JToggleButton btn) {

		Graphics2D g2 = (Graphics2D) g.create();
		Figura figuraActual;
		Point puntoInicio = new Point(btn.getWidth() / 4, btn.getHeight() / 4);
		Color colorPrimario = new Color(98, 154, 198);
		Color colorSecundario = new Color(229, 243, 247);
		boolean dibujarRellena = true;
		int anchura = btn.getWidth() / 2;
		int altura = btn.getHeight() / 2;
		int grosor = 2;

		if (btn.isSelected()) {
			g2.setColor(new Color(205, 228, 252));
			g2.fillRect(0, 0, btn.getWidth(), btn.getHeight());
			g2.setColor(Color.BLACK);
		} else {
			g2.setColor(Color.WHITE);
			g2.fillRect(0, 0, btn.getWidth(), btn.getHeight());
			g2.setColor(Color.BLACK);
		}

		// colorPrimario = g2.getColor();
		figuraActual = figuraADibujarse(btn.getText(), puntoInicio, anchura, altura, colorPrimario, true);

		figuraActual.setDibujarRellena(dibujarRellena);
		figuraActual.setGrosor(grosor);
		figuraActual.setColorSecundario(colorSecundario);
		figuraActual.dibujar(g2);

		g2.dispose();
	}

	public Figura figuraADibujarse(String figuraSeleccionada, Point puntoActual, int anchura, int altura,
			Color colorPrimario, boolean dibujarEnBotones) {

		Figura figuraActual;

		switch (figuraSeleccionada) {
		case "Rectangulo":
			figuraActual = new Rectangulo(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Circulo":
			figuraActual = new Circulo(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Rombo":
			figuraActual = new Rombo(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Triangulo":
			figuraActual = new Triangulo(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Triangulo Rectangulo":
			figuraActual = new TrianguloRectangulo(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Escaleno":
			figuraActual = new Escaleno(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Trapecio":
			figuraActual = new Trapecio(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Estrella":
			figuraActual = new Estrella(puntoActual, anchura, altura, colorPrimario);
			break;
					case "Feria_1":
                                            
			figuraActual = new Feria_1(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Pentagono":
			figuraActual = new Pentagono(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Cometa":
			figuraActual = new Cometa(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Semi Circulo":
			figuraActual = new SemiCirculo(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Pacman":
			figuraActual = new PacMan(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Paralelograma":
			figuraActual = new Paralelograma(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Media Luna":
			figuraActual = new MediaLuna(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Hexagono":
			figuraActual = new Hexagono(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Anillo":
			figuraActual = new Anillo(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Octagono":
			figuraActual = new Octagono(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Cruz":
			figuraActual = new Cruz(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Corazon":
			figuraActual = new Corazon(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Cubeta":
			figuraActual = new Cubeta(puntoActual, colorPrimario, panelDeDibujo);
			break;
		case "Trebol de Tres Hojas":
			figuraActual = new TrebolTresHojas(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Trebol de Cuatro Hojas":
			figuraActual = new TrebolCuatroHojas(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Borrador":
			figuraActual = new Borrador(puntoActual);
			break;
		case "Lapiz":
			figuraActual = new DibujoLibre(puntoActual, colorPrimario);
			break;
		case "Gotero":
			figuraActual = null;
			break;
		case "Flecha Derecha":
			figuraActual = new FlechaDerecha(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Flecha Izquierda":
			figuraActual = new FlechaIzquierda(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Flecha Arriba":
			figuraActual = new FlechaArriba(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Flecha Abajo":
			figuraActual = new FlechaAbajo(puntoActual, anchura, altura, colorPrimario);
			break;
		case "Linea":
			if (dibujarEnBotones) {
				figuraActual = new LineaRedimensionable(new Point((anchura * 4) / 6, (altura * 4) / 6),
						new Point((anchura * 4), (altura * 4)), colorPrimario);
			} else {
				figuraActual = new LineaRedimensionable(puntoActual, puntoActual, colorPrimario);
			}
			break;
		default:
			figuraActual = new DibujoLibre(puntoActual, colorPrimario);
		}

		return figuraActual;
	}

	// Creacion
	private void crearMenuItems() {

		JRadioButtonMenuItem menuItemActual;
		List<JRadioButtonMenuItem> listaDeMenuItem = new ArrayList<>();

		for (String nombreDeFigura : figurasDisponibles) {
			menuItemActual = new JRadioButtonMenuItem(nombreDeFigura);
			grupoMenuItemFiguras.add(menuItemActual);

			listaDeMenuItem.add(menuItemActual);
		}

		for (JRadioButtonMenuItem menu : listaDeMenuItem) {
			menu.addActionListener((e) -> {
				botonSeleccionado = menu.getText();
				System.out.println("Boton Seleccionado es : " + botonSeleccionado);
			});
		}

	}

	private void crearBotonesDeFiguras() {

		JToggleButton btnActual;
		List<JToggleButton> listaDeBotones = new ArrayList<>();
		List<String> botonesExcluidos = Arrays.asList("Cubeta", "Lapiz", "Borrador", "Gotero");

		for (String nombreDeFigura : figurasDisponibles) {

			if (!botonesExcluidos.contains(nombreDeFigura)) {
				btnActual = new JToggleButton(nombreDeFigura) {
					@Override
					protected void paintComponent(Graphics g) {
						figuraADibujarseEnCadaBoton(g, this);
					}

				};
				grupoToogleButtons.add(btnActual);
				btnActual.setToolTipText(nombreDeFigura);
				btnActual.setPreferredSize(new java.awt.Dimension(50, 43));
				btnActual.setRolloverEnabled(false);

				listaDeBotones.add(btnActual);
			}
		}

		for (JToggleButton btn : listaDeBotones) {
			btn.addActionListener((e) -> {
				botonSeleccionado = btn.getText();
				System.out.println("Boton Seleccionado es : " + botonSeleccionado);
				lblFigura.setText(botonSeleccionado);
			});
		}

	}

	private List<String> listaFigurasDisponibles() {

		List<String> listaNombres = new ArrayList<>();

		listaNombres.add("Linea");
		listaNombres.add("Lapiz");
		listaNombres.add("Rectangulo");
		listaNombres.add("Circulo");
		listaNombres.add("Rombo");
		listaNombres.add("Triangulo");
		listaNombres.add("Triangulo Rectangulo");
		listaNombres.add("Escaleno");
		listaNombres.add("Trapecio");
		listaNombres.add("Estrella");
		listaNombres.add("Pentagono");
		listaNombres.add("Cometa");
		listaNombres.add("Semi Circulo");
		listaNombres.add("Pacman");
		listaNombres.add("Paralelograma");
		listaNombres.add("Media Luna");
		listaNombres.add("Hexagono");
		listaNombres.add("Anillo");
		listaNombres.add("Octagono");
		listaNombres.add("Cruz");
		listaNombres.add("Corazon");
		listaNombres.add("Cubeta");
		listaNombres.add("Trebol de Tres Hojas");
		listaNombres.add("Trebol de Cuatro Hojas");
		listaNombres.add("Borrador");
		listaNombres.add("Gotero");
		listaNombres.add("Flecha Derecha");
		listaNombres.add("Flecha Izquierda");
		listaNombres.add("Flecha Arriba");
		listaNombres.add("Flecha Abajo");

		return listaNombres;

	}

	// Funciones
	private void funcionBtnNuevo() {

		if (!panelDeDibujo.getFiguras().isEmpty()) {

			int resultado = JOptionPane.showConfirmDialog(this, "Deseas guardar los cambios ?", this.getTitle(),
					JOptionPane.YES_NO_CANCEL_OPTION);

			if (resultado == 0) {

				if (guardarImagen() == 0) {
					nuevo();
				}

			} else if (resultado == 1) {
				nuevo();
			}
		} else {
			nuevo();
		}
	}

	private void nuevo() {
		panelDeDibujo.getFiguras().clear();
		panelDeDibujo.getFigurasDeshechas().clear();
		panelDeDibujo.setBackground(Color.WHITE);
		panelDeDibujo.repaint();
	}

	private int guardarImagen() {

		JFileChooser f = new JFileChooser();
		String extension = ".png";

		f.setAcceptAllFileFilterUsed(false);
		f.addChoosableFileFilter(new FileNameExtensionFilter(".png", "png", "jpg"));
		f.addChoosableFileFilter(new FileNameExtensionFilter(".jpg", "jpg", "png"));
		f.setDialogTitle("Guardar proyecto");

		int resultado = f.showSaveDialog(this);

		if (resultado == JFileChooser.APPROVE_OPTION) {
			try {
				File archivoAGuardar = f.getSelectedFile();
				extension = f.getFileFilter().getDescription();
				System.out.println("Guardar Como: " + archivoAGuardar.getAbsolutePath());

				BufferedImage bi = new BufferedImage(panelDeDibujo.getWidth(), panelDeDibujo.getHeight(),
						BufferedImage.TYPE_INT_ARGB);
				Graphics2D g = bi.createGraphics();
				panelDeDibujo.paint(g);
				ImageIO.write(bi, "PNG", new File(archivoAGuardar.getAbsolutePath() + extension));
				System.out.println(archivoAGuardar.getName());
			} catch (IOException ex) {
				ex.printStackTrace();
			}
		}

		return resultado;
	}

	private BufferedImage abrirImagen() {

		JFileChooser f = new JFileChooser();
		BufferedImage bimg = null;

		f.setFileFilter(new FileNameExtensionFilter("Solo Aceptan Archivos JPG o PNG", "jpg", "png"));
		f.setCurrentDirectory(new File(System.getProperty("user.home")));
		f.setAcceptAllFileFilterUsed(false);

		int resultado = f.showOpenDialog(this);
		if (resultado == JFileChooser.APPROVE_OPTION) {
			try {
				File archivoSeleccionado = f.getSelectedFile();
				System.out.println("Archivo Seleccionado: " + archivoSeleccionado.getAbsolutePath());

				bimg = ImageIO.read(new File(archivoSeleccionado.getAbsolutePath()));

			} catch (IOException ex) {
				ex.printStackTrace();
			}

			return bimg;
		}
		return bimg;
	}

	private void insertarImagenMovible() {
		BufferedImage bimg = abrirImagen();
		if (bimg != null) {
			botonSeleccionado = "Imagen";
			System.out.println(botonSeleccionado);
			lblFigura.setText(botonSeleccionado);
			panelDeDibujo.setFiguraActual(new Imagen(new Point(0, 0), 100, 100, Color.BLACK, bimg));
			panelDeDibujo.getFiguras().add(panelDeDibujo.getFiguraActual());
			panelDeDibujo.repaint();
		}
	}

	private void preguntarAntesDeCerrar() {

		if (!panelDeDibujo.getFiguras().isEmpty()) {

			int resultado = JOptionPane.showConfirmDialog(this, "Deseas guardar los cambios ?",
					"Dibujante - " + this.getTitle(), JOptionPane.YES_NO_CANCEL_OPTION);

			if (resultado == 0) {
				if (guardarImagen() == 0) {
					System.exit(0);
				}
			} else if (resultado == 1) {
				System.exit(0);
			}
		} else {
			System.exit(0);
		}
	}

	public Color obtenerColorEn(Point puntoActual) {
		BufferedImage image = new BufferedImage(panelDeDibujo.getWidth(), panelDeDibujo.getHeight(),
				BufferedImage.TYPE_4BYTE_ABGR);

		Graphics2D g2 = image.createGraphics();
		panelDeDibujo.paint(g2);
		Color colorObjetivo = new Color(image.getRGB(puntoActual.x, puntoActual.y));
		panelColor1.setBackground(colorObjetivo);
		panelDeDibujo.setFiguraActual(null);
		return colorObjetivo;
	}

	private void seleccionarColorPrimario() {
		colorSeleccionado = JColorChooser.showDialog(this, "Selecciona un color.", colorSeleccionado);
		if (colorSeleccionado != null) {
			panelDeDibujo.setColorActual(colorSeleccionado);
			panelColor1.setBackground(colorSeleccionado);
		}
	}

	private void seleccionarColorSecundario() {
		colorSeleccionado = JColorChooser.showDialog(this, "Selecciona un color.", colorSeleccionado);
		if (colorSeleccionado != null) {
			panelDeDibujo.setColorSecundarioActual(colorSeleccionado);
			panelColor2.setBackground(colorSeleccionado);
		}
	}

	private void deshacer() {

		Stack<Figura> figurasDeshechas = panelDeDibujo.getFigurasDeshechas();
		ArrayList<Figura> figuras = panelDeDibujo.getFiguras();

		if (!figuras.isEmpty()) {
			figurasDeshechas.push(figuras.remove(figuras.size() - 1));
			panelDeDibujo.repaint();
			panelDeDibujo.setFiguraActual(null);
			panelDeDibujo.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
		}
	}

	private void rehacer() {

		Stack<Figura> figurasDeshechas = panelDeDibujo.getFigurasDeshechas();

		ArrayList<Figura> figuras = panelDeDibujo.getFiguras();

		if (!figurasDeshechas.isEmpty()) {

			figuras.add(figurasDeshechas.remove(figurasDeshechas.size() - 1));

			panelDeDibujo.repaint();

		}

	}

	// Getters y Setters
	public boolean getSiseDibujaraRellena() {
		return figuraRellena.isSelected();
	}

	public int getGrosorSeleccionado() {
		return comboGrosor.getSelectedIndex() + 1;
	}

	public String getFiguraSeleccionada() {
		return botonSeleccionado;
	}
}
